### ISSUE TITLE
Langchain integration

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse-js#11]
## Describe the solution you'd like

Add Langchain Integration to the JS/TS SDKs which currently only exists in the Python SDKs.

Why is this important? Reducing the integration effort is key to help more people use Langfuse for their project. The Langchain intgeration (Python only) is currently the fastest way to integrate. It would be awesome if this was also usable for JS/TS Langchain projects.

_I'm happy to support on this, dm on Discord_

## Additional context

- Langchain Callbacks: https://js.langchain.com/docs/modules/callbacks/
- Langfuse Python implementation (probably a lot can be copied/ported)
  - Docs: https://langfuse.com/docs/integrations/langchain
  - Callback handler: https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback.py
  - Tests: https://github.com/langfuse/langfuse-python/blob/main/tests/test_langchain.py

**Comment by maxdeichmann** [comment]
Done and deployed: https://github.com/langfuse/langfuse-js/pull/15
