### ISSUE TITLE
JS SDKs: take env variables for instantiation

### ISSUE THREAD

**Issue by maxdeichmann** [langfuse/langfuse-js#81]
Currently, the Langfuse SDK is not able to take environment variables for configuration. Instead, it relies on options on the constructor.

We want to have one function, which takes `params: { publicKey?: string; secretKey?: string } & LangfuseCoreOptions` and returns the same type.

- This function should have the following behavior:
  - check if values for publicKey, secretKey, or variables within `LangfuseCoreOptions` were provided.
  - If not, check the environment variables and take values from there.
  - If still no variable was defined, log an error if the input param was required but not provided by either the constructor or the env variable. No exception is thrown.
- use existing getEnv utility to access environment variables
- the following variables are available:
  - LANGFUSE_RELEASE
  - LANGFUSE_PUBLIC_KEY
  - LANGFUSE_SECRET_KEY
  - LANGFUSE_DEBUG
  - LANGFUSE_HOST
- Please adjust all environment variables in the CI and tests to reflect the change.
- The function should be called as first action in the two Langfuse objects (<https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse/src/langfuse.ts#L20>,[ https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse-node/src/langfuse-node.ts#L28](https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse-node/src/langfuse-node.ts#L28)) and LangfuseWeb (<https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse/src/langfuse.ts#L76-L77>)
  - As of there, the values returned from that function will be used internally

Overview over all constructors:
- Langfuse: `constructor(params: { publicKey: string; secretKey: string } & LangfuseOptions)`
  - <https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse/src/langfuse.ts#L20>
  - extends `LangfuseCore` and is the object exposed to SDK users for the backend
- Langfuse (node): `constructor(params: { publicKey: string; secretKey: string } & LangfuseOptions)`
  - <https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse-node/src/langfuse-node.ts#L28>
  - Backend SDK for users on old node versions, also extends `LangfuseCore`
- LangfuseCore: `constructor(params: { publicKey: string; secretKey: string } & LangfuseCoreOptions)`
  - extends `LangfuseCoreStateless`
  - Contains additional logic to the `LangfuseCoreStateless` class to improve developer experience
- LangfuseWeb: `constructor(params: { publicKey: string } & LangfuseOptions)`
  - <https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse/src/langfuse.ts#L76-L77>
  - extends `LangfuseWebStateless`
  - This is the SDK which our users can use in react applications
- LangfuseWebStateless: `constructor(params: { publicKey: string } & LangfuseCoreOptions)`
  - extends `LangfuseCoreStateless`
- LangfuseCoreStateless: `constructor(params: { publicKey: string; secretKey?: string } & LangfuseCoreOptions)`
  - <https://github.com/langfuse/langfuse-js/blob/04a75b406010368326bf3e12336f2a9bb9d4c210/langfuse-core/src/index.ts#L100>
  - LangfuseCoreStateless is extended by LangfuseCore
  - LangfuseCoreStateless contains all API calls to our server

**Comment by khareyash05** [comment]
Hey Max! Can i give it a go?

**Comment by gitstart-langfuse** [comment]
Hi @maxdeichmann,

Quick question: It states that we should adjust environment variables in the CI and tests to reflect implemented change, kindly provide an insight on how we can efficiently test functions that take `{ publicKey?: string; secretKey?: string } & LangfuseCoreOptions` as params.
